# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
    dev:
        desc: Start the development server (using WebKit2 for Ubuntu 24)
        cmd: wails dev -tags webkit2_41

    build:
        desc: Build production Wails app for Windows with version injection
        cmds:
            - |
                wails build -platform windows -ldflags "\
                  -X main.Version={{.VERSION}} \
                  -X main.BuildTime={{.BUILDTIME}} \
                  -X main.GitCommit={{.GITCOMMIT}}" \
                  -tags production
        vars:
            VERSION:
                sh: git describe --tags --always --dirty 2>/dev/null || echo "0.1.0-dev"
            BUILDTIME:
                sh: date -u '+%Y-%m-%d_%H:%M:%S'
            GITCOMMIT:
                sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
