// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package sqlc

import (
	"context"
	"database/sql"
)

const configExists = `-- name: ConfigExists :one
SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS config_exists FROM config WHERE id = 1
`

// Check if configuration exists
func (q *Queries) ConfigExists(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.configExistsStmt, configExists)
	var config_exists int64
	err := row.Scan(&config_exists)
	return config_exists, err
}

const createConfig = `-- name: CreateConfig :exec
INSERT INTO config (
    id, owner_email, ca_name, hostname_suffix, validity_period_days,
    default_organization, default_organizational_unit,
    default_city, default_state, default_country, default_key_size
) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateConfigParams struct {
	OwnerEmail                string         `json:"owner_email"`
	CaName                    string         `json:"ca_name"`
	HostnameSuffix            string         `json:"hostname_suffix"`
	ValidityPeriodDays        int64          `json:"validity_period_days"`
	DefaultOrganization       string         `json:"default_organization"`
	DefaultOrganizationalUnit sql.NullString `json:"default_organizational_unit"`
	DefaultCity               string         `json:"default_city"`
	DefaultState              string         `json:"default_state"`
	DefaultCountry            string         `json:"default_country"`
	DefaultKeySize            int64          `json:"default_key_size"`
}

// Create the initial configuration
func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) error {
	_, err := q.exec(ctx, q.createConfigStmt, createConfig,
		arg.OwnerEmail,
		arg.CaName,
		arg.HostnameSuffix,
		arg.ValidityPeriodDays,
		arg.DefaultOrganization,
		arg.DefaultOrganizationalUnit,
		arg.DefaultCity,
		arg.DefaultState,
		arg.DefaultCountry,
		arg.DefaultKeySize,
	)
	return err
}

const getConfig = `-- name: GetConfig :one
SELECT id, owner_email, ca_name, hostname_suffix, validity_period_days,
       default_organization, default_organizational_unit,
       default_city, default_state, default_country, default_key_size,
       is_configured,
       created_at, last_modified
FROM config WHERE id = 1 LIMIT 1
`

// Get the configuration (single row)
func (q *Queries) GetConfig(ctx context.Context) (Config, error) {
	row := q.queryRow(ctx, q.getConfigStmt, getConfig)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.OwnerEmail,
		&i.CaName,
		&i.HostnameSuffix,
		&i.ValidityPeriodDays,
		&i.DefaultOrganization,
		&i.DefaultOrganizationalUnit,
		&i.DefaultCity,
		&i.DefaultState,
		&i.DefaultCountry,
		&i.DefaultKeySize,
		&i.IsConfigured,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const isConfigured = `-- name: IsConfigured :one
SELECT is_configured FROM config WHERE id = 1 LIMIT 1
`

// Check if initial setup is complete
func (q *Queries) IsConfigured(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.isConfiguredStmt, isConfigured)
	var is_configured int64
	err := row.Scan(&is_configured)
	return is_configured, err
}

const setConfigured = `-- name: SetConfigured :exec
UPDATE config
SET is_configured = 1,
    last_modified = unixepoch('now')
WHERE id = 1
`

// Mark setup as complete
func (q *Queries) SetConfigured(ctx context.Context) error {
	_, err := q.exec(ctx, q.setConfiguredStmt, setConfigured)
	return err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE config
SET owner_email = ?,
    ca_name = ?,
    hostname_suffix = ?,
    validity_period_days = ?,
    default_organization = ?,
    default_organizational_unit = ?,
    default_city = ?,
    default_state = ?,
    default_country = ?,
    default_key_size = ?,
    last_modified = unixepoch('now')
WHERE id = 1
`

type UpdateConfigParams struct {
	OwnerEmail                string         `json:"owner_email"`
	CaName                    string         `json:"ca_name"`
	HostnameSuffix            string         `json:"hostname_suffix"`
	ValidityPeriodDays        int64          `json:"validity_period_days"`
	DefaultOrganization       string         `json:"default_organization"`
	DefaultOrganizationalUnit sql.NullString `json:"default_organizational_unit"`
	DefaultCity               string         `json:"default_city"`
	DefaultState              string         `json:"default_state"`
	DefaultCountry            string         `json:"default_country"`
	DefaultKeySize            int64          `json:"default_key_size"`
}

// Update configuration (preserves is_configured flag)
func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.exec(ctx, q.updateConfigStmt, updateConfig,
		arg.OwnerEmail,
		arg.CaName,
		arg.HostnameSuffix,
		arg.ValidityPeriodDays,
		arg.DefaultOrganization,
		arg.DefaultOrganizationalUnit,
		arg.DefaultCity,
		arg.DefaultState,
		arg.DefaultCountry,
		arg.DefaultKeySize,
	)
	return err
}
