// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.activateCertificateStmt, err = db.PrepareContext(ctx, activateCertificate); err != nil {
		return nil, fmt.Errorf("error preparing query ActivateCertificate: %w", err)
	}
	if q.certificateExistsStmt, err = db.PrepareContext(ctx, certificateExists); err != nil {
		return nil, fmt.Errorf("error preparing query CertificateExists: %w", err)
	}
	if q.clearPendingCSRStmt, err = db.PrepareContext(ctx, clearPendingCSR); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPendingCSR: %w", err)
	}
	if q.configExistsStmt, err = db.PrepareContext(ctx, configExists); err != nil {
		return nil, fmt.Errorf("error preparing query ConfigExists: %w", err)
	}
	if q.createCertificateStmt, err = db.PrepareContext(ctx, createCertificate); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCertificate: %w", err)
	}
	if q.createConfigStmt, err = db.PrepareContext(ctx, createConfig); err != nil {
		return nil, fmt.Errorf("error preparing query CreateConfig: %w", err)
	}
	if q.deleteAllCertificatesStmt, err = db.PrepareContext(ctx, deleteAllCertificates); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllCertificates: %w", err)
	}
	if q.deleteCertificateStmt, err = db.PrepareContext(ctx, deleteCertificate); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCertificate: %w", err)
	}
	if q.getCertificateByHostnameStmt, err = db.PrepareContext(ctx, getCertificateByHostname); err != nil {
		return nil, fmt.Errorf("error preparing query GetCertificateByHostname: %w", err)
	}
	if q.getConfigStmt, err = db.PrepareContext(ctx, getConfig); err != nil {
		return nil, fmt.Errorf("error preparing query GetConfig: %w", err)
	}
	if q.isConfiguredStmt, err = db.PrepareContext(ctx, isConfigured); err != nil {
		return nil, fmt.Errorf("error preparing query IsConfigured: %w", err)
	}
	if q.listAllCertificatesStmt, err = db.PrepareContext(ctx, listAllCertificates); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllCertificates: %w", err)
	}
	if q.restoreCertificateStmt, err = db.PrepareContext(ctx, restoreCertificate); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreCertificate: %w", err)
	}
	if q.setConfiguredStmt, err = db.PrepareContext(ctx, setConfigured); err != nil {
		return nil, fmt.Errorf("error preparing query SetConfigured: %w", err)
	}
	if q.updateCertificateNoteStmt, err = db.PrepareContext(ctx, updateCertificateNote); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCertificateNote: %w", err)
	}
	if q.updateCertificateReadOnlyStmt, err = db.PrepareContext(ctx, updateCertificateReadOnly); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCertificateReadOnly: %w", err)
	}
	if q.updateConfigStmt, err = db.PrepareContext(ctx, updateConfig); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateConfig: %w", err)
	}
	if q.updatePendingCSRStmt, err = db.PrepareContext(ctx, updatePendingCSR); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePendingCSR: %w", err)
	}
	if q.updatePendingNoteStmt, err = db.PrepareContext(ctx, updatePendingNote); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePendingNote: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.activateCertificateStmt != nil {
		if cerr := q.activateCertificateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing activateCertificateStmt: %w", cerr)
		}
	}
	if q.certificateExistsStmt != nil {
		if cerr := q.certificateExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing certificateExistsStmt: %w", cerr)
		}
	}
	if q.clearPendingCSRStmt != nil {
		if cerr := q.clearPendingCSRStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPendingCSRStmt: %w", cerr)
		}
	}
	if q.configExistsStmt != nil {
		if cerr := q.configExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing configExistsStmt: %w", cerr)
		}
	}
	if q.createCertificateStmt != nil {
		if cerr := q.createCertificateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCertificateStmt: %w", cerr)
		}
	}
	if q.createConfigStmt != nil {
		if cerr := q.createConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createConfigStmt: %w", cerr)
		}
	}
	if q.deleteAllCertificatesStmt != nil {
		if cerr := q.deleteAllCertificatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllCertificatesStmt: %w", cerr)
		}
	}
	if q.deleteCertificateStmt != nil {
		if cerr := q.deleteCertificateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCertificateStmt: %w", cerr)
		}
	}
	if q.getCertificateByHostnameStmt != nil {
		if cerr := q.getCertificateByHostnameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCertificateByHostnameStmt: %w", cerr)
		}
	}
	if q.getConfigStmt != nil {
		if cerr := q.getConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getConfigStmt: %w", cerr)
		}
	}
	if q.isConfiguredStmt != nil {
		if cerr := q.isConfiguredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isConfiguredStmt: %w", cerr)
		}
	}
	if q.listAllCertificatesStmt != nil {
		if cerr := q.listAllCertificatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllCertificatesStmt: %w", cerr)
		}
	}
	if q.restoreCertificateStmt != nil {
		if cerr := q.restoreCertificateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreCertificateStmt: %w", cerr)
		}
	}
	if q.setConfiguredStmt != nil {
		if cerr := q.setConfiguredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setConfiguredStmt: %w", cerr)
		}
	}
	if q.updateCertificateNoteStmt != nil {
		if cerr := q.updateCertificateNoteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCertificateNoteStmt: %w", cerr)
		}
	}
	if q.updateCertificateReadOnlyStmt != nil {
		if cerr := q.updateCertificateReadOnlyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCertificateReadOnlyStmt: %w", cerr)
		}
	}
	if q.updateConfigStmt != nil {
		if cerr := q.updateConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateConfigStmt: %w", cerr)
		}
	}
	if q.updatePendingCSRStmt != nil {
		if cerr := q.updatePendingCSRStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePendingCSRStmt: %w", cerr)
		}
	}
	if q.updatePendingNoteStmt != nil {
		if cerr := q.updatePendingNoteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePendingNoteStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	activateCertificateStmt       *sql.Stmt
	certificateExistsStmt         *sql.Stmt
	clearPendingCSRStmt           *sql.Stmt
	configExistsStmt              *sql.Stmt
	createCertificateStmt         *sql.Stmt
	createConfigStmt              *sql.Stmt
	deleteAllCertificatesStmt     *sql.Stmt
	deleteCertificateStmt         *sql.Stmt
	getCertificateByHostnameStmt  *sql.Stmt
	getConfigStmt                 *sql.Stmt
	isConfiguredStmt              *sql.Stmt
	listAllCertificatesStmt       *sql.Stmt
	restoreCertificateStmt        *sql.Stmt
	setConfiguredStmt             *sql.Stmt
	updateCertificateNoteStmt     *sql.Stmt
	updateCertificateReadOnlyStmt *sql.Stmt
	updateConfigStmt              *sql.Stmt
	updatePendingCSRStmt          *sql.Stmt
	updatePendingNoteStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		activateCertificateStmt:       q.activateCertificateStmt,
		certificateExistsStmt:         q.certificateExistsStmt,
		clearPendingCSRStmt:           q.clearPendingCSRStmt,
		configExistsStmt:              q.configExistsStmt,
		createCertificateStmt:         q.createCertificateStmt,
		createConfigStmt:              q.createConfigStmt,
		deleteAllCertificatesStmt:     q.deleteAllCertificatesStmt,
		deleteCertificateStmt:         q.deleteCertificateStmt,
		getCertificateByHostnameStmt:  q.getCertificateByHostnameStmt,
		getConfigStmt:                 q.getConfigStmt,
		isConfiguredStmt:              q.isConfiguredStmt,
		listAllCertificatesStmt:       q.listAllCertificatesStmt,
		restoreCertificateStmt:        q.restoreCertificateStmt,
		setConfiguredStmt:             q.setConfiguredStmt,
		updateCertificateNoteStmt:     q.updateCertificateNoteStmt,
		updateCertificateReadOnlyStmt: q.updateCertificateReadOnlyStmt,
		updateConfigStmt:              q.updateConfigStmt,
		updatePendingCSRStmt:          q.updatePendingCSRStmt,
		updatePendingNoteStmt:         q.updatePendingNoteStmt,
	}
}
