// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.activateCertificateStmt, err = db.PrepareContext(ctx, activateCertificate); err != nil {
		return nil, fmt.Errorf("error preparing query ActivateCertificate: %w", err)
	}
	if q.addHistoryEntryStmt, err = db.PrepareContext(ctx, addHistoryEntry); err != nil {
		return nil, fmt.Errorf("error preparing query AddHistoryEntry: %w", err)
	}
	if q.certificateExistsStmt, err = db.PrepareContext(ctx, certificateExists); err != nil {
		return nil, fmt.Errorf("error preparing query CertificateExists: %w", err)
	}
	if q.clearPendingCSRStmt, err = db.PrepareContext(ctx, clearPendingCSR); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPendingCSR: %w", err)
	}
	if q.configExistsStmt, err = db.PrepareContext(ctx, configExists); err != nil {
		return nil, fmt.Errorf("error preparing query ConfigExists: %w", err)
	}
	if q.countAllSecurityKeysStmt, err = db.PrepareContext(ctx, countAllSecurityKeys); err != nil {
		return nil, fmt.Errorf("error preparing query CountAllSecurityKeys: %w", err)
	}
	if q.countSecurityKeysByMethodStmt, err = db.PrepareContext(ctx, countSecurityKeysByMethod); err != nil {
		return nil, fmt.Errorf("error preparing query CountSecurityKeysByMethod: %w", err)
	}
	if q.createCertificateStmt, err = db.PrepareContext(ctx, createCertificate); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCertificate: %w", err)
	}
	if q.createConfigStmt, err = db.PrepareContext(ctx, createConfig); err != nil {
		return nil, fmt.Errorf("error preparing query CreateConfig: %w", err)
	}
	if q.deleteAllCertificatesStmt, err = db.PrepareContext(ctx, deleteAllCertificates); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllCertificates: %w", err)
	}
	if q.deleteCertificateStmt, err = db.PrepareContext(ctx, deleteCertificate); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCertificate: %w", err)
	}
	if q.deleteCertificateHistoryStmt, err = db.PrepareContext(ctx, deleteCertificateHistory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCertificateHistory: %w", err)
	}
	if q.deleteSecurityKeyStmt, err = db.PrepareContext(ctx, deleteSecurityKey); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSecurityKey: %w", err)
	}
	if q.deleteSecurityKeysByMethodStmt, err = db.PrepareContext(ctx, deleteSecurityKeysByMethod); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSecurityKeysByMethod: %w", err)
	}
	if q.getCertificateByHostnameStmt, err = db.PrepareContext(ctx, getCertificateByHostname); err != nil {
		return nil, fmt.Errorf("error preparing query GetCertificateByHostname: %w", err)
	}
	if q.getCertificateHistoryStmt, err = db.PrepareContext(ctx, getCertificateHistory); err != nil {
		return nil, fmt.Errorf("error preparing query GetCertificateHistory: %w", err)
	}
	if q.getConfigStmt, err = db.PrepareContext(ctx, getConfig); err != nil {
		return nil, fmt.Errorf("error preparing query GetConfig: %w", err)
	}
	if q.getSecurityKeyByIDStmt, err = db.PrepareContext(ctx, getSecurityKeyByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSecurityKeyByID: %w", err)
	}
	if q.getSecurityKeysByMethodStmt, err = db.PrepareContext(ctx, getSecurityKeysByMethod); err != nil {
		return nil, fmt.Errorf("error preparing query GetSecurityKeysByMethod: %w", err)
	}
	if q.getUpdateHistoryStmt, err = db.PrepareContext(ctx, getUpdateHistory); err != nil {
		return nil, fmt.Errorf("error preparing query GetUpdateHistory: %w", err)
	}
	if q.hasAnySecurityKeysStmt, err = db.PrepareContext(ctx, hasAnySecurityKeys); err != nil {
		return nil, fmt.Errorf("error preparing query HasAnySecurityKeys: %w", err)
	}
	if q.insertSecurityKeyStmt, err = db.PrepareContext(ctx, insertSecurityKey); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSecurityKey: %w", err)
	}
	if q.isConfiguredStmt, err = db.PrepareContext(ctx, isConfigured); err != nil {
		return nil, fmt.Errorf("error preparing query IsConfigured: %w", err)
	}
	if q.listAllCertificatesStmt, err = db.PrepareContext(ctx, listAllCertificates); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllCertificates: %w", err)
	}
	if q.listSecurityKeysStmt, err = db.PrepareContext(ctx, listSecurityKeys); err != nil {
		return nil, fmt.Errorf("error preparing query ListSecurityKeys: %w", err)
	}
	if q.recordUpdateStmt, err = db.PrepareContext(ctx, recordUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query RecordUpdate: %w", err)
	}
	if q.restoreCertificateStmt, err = db.PrepareContext(ctx, restoreCertificate); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreCertificate: %w", err)
	}
	if q.setConfiguredStmt, err = db.PrepareContext(ctx, setConfigured); err != nil {
		return nil, fmt.Errorf("error preparing query SetConfigured: %w", err)
	}
	if q.updateCertificateNoteStmt, err = db.PrepareContext(ctx, updateCertificateNote); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCertificateNote: %w", err)
	}
	if q.updateCertificateReadOnlyStmt, err = db.PrepareContext(ctx, updateCertificateReadOnly); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCertificateReadOnly: %w", err)
	}
	if q.updateConfigStmt, err = db.PrepareContext(ctx, updateConfig); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateConfig: %w", err)
	}
	if q.updateEncryptedKeysStmt, err = db.PrepareContext(ctx, updateEncryptedKeys); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateEncryptedKeys: %w", err)
	}
	if q.updatePendingCSRStmt, err = db.PrepareContext(ctx, updatePendingCSR); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePendingCSR: %w", err)
	}
	if q.updatePendingNoteStmt, err = db.PrepareContext(ctx, updatePendingNote); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePendingNote: %w", err)
	}
	if q.updateSecurityKeyLastUsedStmt, err = db.PrepareContext(ctx, updateSecurityKeyLastUsed); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSecurityKeyLastUsed: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.activateCertificateStmt != nil {
		if cerr := q.activateCertificateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing activateCertificateStmt: %w", cerr)
		}
	}
	if q.addHistoryEntryStmt != nil {
		if cerr := q.addHistoryEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addHistoryEntryStmt: %w", cerr)
		}
	}
	if q.certificateExistsStmt != nil {
		if cerr := q.certificateExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing certificateExistsStmt: %w", cerr)
		}
	}
	if q.clearPendingCSRStmt != nil {
		if cerr := q.clearPendingCSRStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPendingCSRStmt: %w", cerr)
		}
	}
	if q.configExistsStmt != nil {
		if cerr := q.configExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing configExistsStmt: %w", cerr)
		}
	}
	if q.countAllSecurityKeysStmt != nil {
		if cerr := q.countAllSecurityKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAllSecurityKeysStmt: %w", cerr)
		}
	}
	if q.countSecurityKeysByMethodStmt != nil {
		if cerr := q.countSecurityKeysByMethodStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countSecurityKeysByMethodStmt: %w", cerr)
		}
	}
	if q.createCertificateStmt != nil {
		if cerr := q.createCertificateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCertificateStmt: %w", cerr)
		}
	}
	if q.createConfigStmt != nil {
		if cerr := q.createConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createConfigStmt: %w", cerr)
		}
	}
	if q.deleteAllCertificatesStmt != nil {
		if cerr := q.deleteAllCertificatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllCertificatesStmt: %w", cerr)
		}
	}
	if q.deleteCertificateStmt != nil {
		if cerr := q.deleteCertificateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCertificateStmt: %w", cerr)
		}
	}
	if q.deleteCertificateHistoryStmt != nil {
		if cerr := q.deleteCertificateHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCertificateHistoryStmt: %w", cerr)
		}
	}
	if q.deleteSecurityKeyStmt != nil {
		if cerr := q.deleteSecurityKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSecurityKeyStmt: %w", cerr)
		}
	}
	if q.deleteSecurityKeysByMethodStmt != nil {
		if cerr := q.deleteSecurityKeysByMethodStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSecurityKeysByMethodStmt: %w", cerr)
		}
	}
	if q.getCertificateByHostnameStmt != nil {
		if cerr := q.getCertificateByHostnameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCertificateByHostnameStmt: %w", cerr)
		}
	}
	if q.getCertificateHistoryStmt != nil {
		if cerr := q.getCertificateHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCertificateHistoryStmt: %w", cerr)
		}
	}
	if q.getConfigStmt != nil {
		if cerr := q.getConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getConfigStmt: %w", cerr)
		}
	}
	if q.getSecurityKeyByIDStmt != nil {
		if cerr := q.getSecurityKeyByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSecurityKeyByIDStmt: %w", cerr)
		}
	}
	if q.getSecurityKeysByMethodStmt != nil {
		if cerr := q.getSecurityKeysByMethodStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSecurityKeysByMethodStmt: %w", cerr)
		}
	}
	if q.getUpdateHistoryStmt != nil {
		if cerr := q.getUpdateHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUpdateHistoryStmt: %w", cerr)
		}
	}
	if q.hasAnySecurityKeysStmt != nil {
		if cerr := q.hasAnySecurityKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasAnySecurityKeysStmt: %w", cerr)
		}
	}
	if q.insertSecurityKeyStmt != nil {
		if cerr := q.insertSecurityKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSecurityKeyStmt: %w", cerr)
		}
	}
	if q.isConfiguredStmt != nil {
		if cerr := q.isConfiguredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isConfiguredStmt: %w", cerr)
		}
	}
	if q.listAllCertificatesStmt != nil {
		if cerr := q.listAllCertificatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllCertificatesStmt: %w", cerr)
		}
	}
	if q.listSecurityKeysStmt != nil {
		if cerr := q.listSecurityKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSecurityKeysStmt: %w", cerr)
		}
	}
	if q.recordUpdateStmt != nil {
		if cerr := q.recordUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordUpdateStmt: %w", cerr)
		}
	}
	if q.restoreCertificateStmt != nil {
		if cerr := q.restoreCertificateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreCertificateStmt: %w", cerr)
		}
	}
	if q.setConfiguredStmt != nil {
		if cerr := q.setConfiguredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setConfiguredStmt: %w", cerr)
		}
	}
	if q.updateCertificateNoteStmt != nil {
		if cerr := q.updateCertificateNoteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCertificateNoteStmt: %w", cerr)
		}
	}
	if q.updateCertificateReadOnlyStmt != nil {
		if cerr := q.updateCertificateReadOnlyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCertificateReadOnlyStmt: %w", cerr)
		}
	}
	if q.updateConfigStmt != nil {
		if cerr := q.updateConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateConfigStmt: %w", cerr)
		}
	}
	if q.updateEncryptedKeysStmt != nil {
		if cerr := q.updateEncryptedKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateEncryptedKeysStmt: %w", cerr)
		}
	}
	if q.updatePendingCSRStmt != nil {
		if cerr := q.updatePendingCSRStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePendingCSRStmt: %w", cerr)
		}
	}
	if q.updatePendingNoteStmt != nil {
		if cerr := q.updatePendingNoteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePendingNoteStmt: %w", cerr)
		}
	}
	if q.updateSecurityKeyLastUsedStmt != nil {
		if cerr := q.updateSecurityKeyLastUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSecurityKeyLastUsedStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                             DBTX
	tx                             *sql.Tx
	activateCertificateStmt        *sql.Stmt
	addHistoryEntryStmt            *sql.Stmt
	certificateExistsStmt          *sql.Stmt
	clearPendingCSRStmt            *sql.Stmt
	configExistsStmt               *sql.Stmt
	countAllSecurityKeysStmt       *sql.Stmt
	countSecurityKeysByMethodStmt  *sql.Stmt
	createCertificateStmt          *sql.Stmt
	createConfigStmt               *sql.Stmt
	deleteAllCertificatesStmt      *sql.Stmt
	deleteCertificateStmt          *sql.Stmt
	deleteCertificateHistoryStmt   *sql.Stmt
	deleteSecurityKeyStmt          *sql.Stmt
	deleteSecurityKeysByMethodStmt *sql.Stmt
	getCertificateByHostnameStmt   *sql.Stmt
	getCertificateHistoryStmt      *sql.Stmt
	getConfigStmt                  *sql.Stmt
	getSecurityKeyByIDStmt         *sql.Stmt
	getSecurityKeysByMethodStmt    *sql.Stmt
	getUpdateHistoryStmt           *sql.Stmt
	hasAnySecurityKeysStmt         *sql.Stmt
	insertSecurityKeyStmt          *sql.Stmt
	isConfiguredStmt               *sql.Stmt
	listAllCertificatesStmt        *sql.Stmt
	listSecurityKeysStmt           *sql.Stmt
	recordUpdateStmt               *sql.Stmt
	restoreCertificateStmt         *sql.Stmt
	setConfiguredStmt              *sql.Stmt
	updateCertificateNoteStmt      *sql.Stmt
	updateCertificateReadOnlyStmt  *sql.Stmt
	updateConfigStmt               *sql.Stmt
	updateEncryptedKeysStmt        *sql.Stmt
	updatePendingCSRStmt           *sql.Stmt
	updatePendingNoteStmt          *sql.Stmt
	updateSecurityKeyLastUsedStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                             tx,
		tx:                             tx,
		activateCertificateStmt:        q.activateCertificateStmt,
		addHistoryEntryStmt:            q.addHistoryEntryStmt,
		certificateExistsStmt:          q.certificateExistsStmt,
		clearPendingCSRStmt:            q.clearPendingCSRStmt,
		configExistsStmt:               q.configExistsStmt,
		countAllSecurityKeysStmt:       q.countAllSecurityKeysStmt,
		countSecurityKeysByMethodStmt:  q.countSecurityKeysByMethodStmt,
		createCertificateStmt:          q.createCertificateStmt,
		createConfigStmt:               q.createConfigStmt,
		deleteAllCertificatesStmt:      q.deleteAllCertificatesStmt,
		deleteCertificateStmt:          q.deleteCertificateStmt,
		deleteCertificateHistoryStmt:   q.deleteCertificateHistoryStmt,
		deleteSecurityKeyStmt:          q.deleteSecurityKeyStmt,
		deleteSecurityKeysByMethodStmt: q.deleteSecurityKeysByMethodStmt,
		getCertificateByHostnameStmt:   q.getCertificateByHostnameStmt,
		getCertificateHistoryStmt:      q.getCertificateHistoryStmt,
		getConfigStmt:                  q.getConfigStmt,
		getSecurityKeyByIDStmt:         q.getSecurityKeyByIDStmt,
		getSecurityKeysByMethodStmt:    q.getSecurityKeysByMethodStmt,
		getUpdateHistoryStmt:           q.getUpdateHistoryStmt,
		hasAnySecurityKeysStmt:         q.hasAnySecurityKeysStmt,
		insertSecurityKeyStmt:          q.insertSecurityKeyStmt,
		isConfiguredStmt:               q.isConfiguredStmt,
		listAllCertificatesStmt:        q.listAllCertificatesStmt,
		listSecurityKeysStmt:           q.listSecurityKeysStmt,
		recordUpdateStmt:               q.recordUpdateStmt,
		restoreCertificateStmt:         q.restoreCertificateStmt,
		setConfiguredStmt:              q.setConfiguredStmt,
		updateCertificateNoteStmt:      q.updateCertificateNoteStmt,
		updateCertificateReadOnlyStmt:  q.updateCertificateReadOnlyStmt,
		updateConfigStmt:               q.updateConfigStmt,
		updateEncryptedKeysStmt:        q.updateEncryptedKeysStmt,
		updatePendingCSRStmt:           q.updatePendingCSRStmt,
		updatePendingNoteStmt:          q.updatePendingNoteStmt,
		updateSecurityKeyLastUsedStmt:  q.updateSecurityKeyLastUsedStmt,
	}
}
