// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"
)

const addHistoryEntry = `-- name: AddHistoryEntry :exec

INSERT INTO certificate_history (hostname, event_type, message)
VALUES (?, ?, ?)
`

type AddHistoryEntryParams struct {
	Hostname  string `json:"hostname"`
	EventType string `json:"event_type"`
	Message   string `json:"message"`
}

// Certificate history queries
// Add a new history entry for a certificate
func (q *Queries) AddHistoryEntry(ctx context.Context, arg AddHistoryEntryParams) error {
	_, err := q.exec(ctx, q.addHistoryEntryStmt, addHistoryEntry, arg.Hostname, arg.EventType, arg.Message)
	return err
}

const deleteCertificateHistory = `-- name: DeleteCertificateHistory :exec
DELETE FROM certificate_history WHERE hostname = ?
`

// Delete all history entries for a certificate (used when certificate is deleted)
func (q *Queries) DeleteCertificateHistory(ctx context.Context, hostname string) error {
	_, err := q.exec(ctx, q.deleteCertificateHistoryStmt, deleteCertificateHistory, hostname)
	return err
}

const getCertificateHistory = `-- name: GetCertificateHistory :many
SELECT id, hostname, event_type, message, created_at
FROM certificate_history
WHERE hostname = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetCertificateHistoryParams struct {
	Hostname string `json:"hostname"`
	Limit    int64  `json:"limit"`
}

// Get history entries for a certificate, ordered by most recent first
func (q *Queries) GetCertificateHistory(ctx context.Context, arg GetCertificateHistoryParams) ([]CertificateHistory, error) {
	rows, err := q.query(ctx, q.getCertificateHistoryStmt, getCertificateHistory, arg.Hostname, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CertificateHistory
	for rows.Next() {
		var i CertificateHistory
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.EventType,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
