// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Certificate struct {
	Hostname                   string         `json:"hostname"`
	EncryptedPrivateKey        []byte         `json:"encrypted_private_key"`
	PendingCsrPem              sql.NullString `json:"pending_csr_pem"`
	CertificatePem             sql.NullString `json:"certificate_pem"`
	PendingEncryptedPrivateKey []byte         `json:"pending_encrypted_private_key"`
	CreatedAt                  int64          `json:"created_at"`
	ExpiresAt                  sql.NullInt64  `json:"expires_at"`
	LastModified               int64          `json:"last_modified"`
	Note                       sql.NullString `json:"note"`
	PendingNote                sql.NullString `json:"pending_note"`
	ReadOnly                   int64          `json:"read_only"`
}

type Config struct {
	ID                        int64          `json:"id"`
	OwnerEmail                string         `json:"owner_email"`
	CaName                    string         `json:"ca_name"`
	HostnameSuffix            string         `json:"hostname_suffix"`
	ValidityPeriodDays        int64          `json:"validity_period_days"`
	DefaultOrganization       string         `json:"default_organization"`
	DefaultOrganizationalUnit sql.NullString `json:"default_organizational_unit"`
	DefaultCity               string         `json:"default_city"`
	DefaultState              string         `json:"default_state"`
	DefaultCountry            string         `json:"default_country"`
	DefaultKeySize            int64          `json:"default_key_size"`
	IsConfigured              int64          `json:"is_configured"`
	CreatedAt                 int64          `json:"created_at"`
	LastModified              int64          `json:"last_modified"`
}
