// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Activate certificate after upload (unified for initial or renewal)
	// Move pending key to active column, store certificate, clear pending columns
	// COALESCE ensures existing key is preserved if pending key is somehow NULL
	ActivateCertificate(ctx context.Context, arg ActivateCertificateParams) error
	// Certificate history queries
	// Add a new history entry for a certificate
	AddHistoryEntry(ctx context.Context, arg AddHistoryEntryParams) error
	// Check if certificate exists by hostname
	CertificateExists(ctx context.Context, hostname string) (int64, error)
	// Clear pending CSR and pending key without deleting the certificate
	ClearPendingCSR(ctx context.Context, hostname string) error
	// Check if configuration exists
	ConfigExists(ctx context.Context) (int64, error)
	// Count all security keys
	CountAllSecurityKeys(ctx context.Context) (int64, error)
	// Count security keys of a specific method
	CountSecurityKeysByMethod(ctx context.Context, method string) (int64, error)
	// Create a new certificate entry with all fields
	CreateCertificate(ctx context.Context, arg CreateCertificateParams) error
	// Create the initial configuration
	CreateConfig(ctx context.Context, arg CreateConfigParams) error
	// Delete all certificates
	DeleteAllCertificates(ctx context.Context) error
	// Delete a certificate
	DeleteCertificate(ctx context.Context, hostname string) error
	// Delete all history entries for a certificate (used when certificate is deleted)
	DeleteCertificateHistory(ctx context.Context, hostname string) error
	// Delete a security key by ID
	DeleteSecurityKey(ctx context.Context, id int64) error
	// Delete all security keys of a specific method
	DeleteSecurityKeysByMethod(ctx context.Context, method string) error
	// Get a certificate by hostname
	GetCertificateByHostname(ctx context.Context, hostname string) (Certificate, error)
	// Get history entries for a certificate, ordered by most recent first
	GetCertificateHistory(ctx context.Context, arg GetCertificateHistoryParams) ([]CertificateHistory, error)
	// Get the configuration (single row)
	GetConfig(ctx context.Context) (Config, error)
	// Get a single security key by ID
	GetSecurityKeyByID(ctx context.Context, id int64) (SecurityKey, error)
	// Get security keys filtered by method type
	GetSecurityKeysByMethod(ctx context.Context, method string) ([]SecurityKey, error)
	// Get recent update history entries, newest first
	GetUpdateHistory(ctx context.Context, limit int64) ([]UpdateHistory, error)
	// Check if any security keys exist
	HasAnySecurityKeys(ctx context.Context) (int64, error)
	// Insert a new security key and return the created row
	InsertSecurityKey(ctx context.Context, arg InsertSecurityKeyParams) (SecurityKey, error)
	// Check if initial setup is complete
	IsConfigured(ctx context.Context) (int64, error)
	// List all certificates ordered by creation date
	ListAllCertificates(ctx context.Context) ([]Certificate, error)
	// List all security keys ordered by creation date
	ListSecurityKeys(ctx context.Context) ([]SecurityKey, error)
	// Update history queries
	// Record an update attempt (success or failure)
	RecordUpdate(ctx context.Context, arg RecordUpdateParams) error
	// Restore a complete certificate from backup in a single operation
	RestoreCertificate(ctx context.Context, arg RestoreCertificateParams) error
	// Mark setup as complete
	SetConfigured(ctx context.Context) error
	// Update the note field for a certificate
	UpdateCertificateNote(ctx context.Context, arg UpdateCertificateNoteParams) error
	// Mark certificate as read-only
	UpdateCertificateReadOnly(ctx context.Context, arg UpdateCertificateReadOnlyParams) error
	// Update configuration (preserves is_configured flag)
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) error
	// Update encrypted private key fields (for key rotation)
	UpdateEncryptedKeys(ctx context.Context, arg UpdateEncryptedKeysParams) error
	// Store or update pending CSR and key (unified for initial generation or renewal)
	UpdatePendingCSR(ctx context.Context, arg UpdatePendingCSRParams) error
	// Update the pending note field
	UpdatePendingNote(ctx context.Context, arg UpdatePendingNoteParams) error
	// Update the last_used_at timestamp for a security key
	UpdateSecurityKeyLastUsed(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
