// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updates.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getUpdateHistory = `-- name: GetUpdateHistory :many
SELECT id, from_version, to_version, status, error_message, created_at
FROM update_history
ORDER BY created_at DESC
LIMIT ?
`

// Get recent update history entries, newest first
func (q *Queries) GetUpdateHistory(ctx context.Context, limit int64) ([]UpdateHistory, error) {
	rows, err := q.query(ctx, q.getUpdateHistoryStmt, getUpdateHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpdateHistory
	for rows.Next() {
		var i UpdateHistory
		if err := rows.Scan(
			&i.ID,
			&i.FromVersion,
			&i.ToVersion,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUpdate = `-- name: RecordUpdate :exec

INSERT INTO update_history (from_version, to_version, status, error_message)
VALUES (?, ?, ?, ?)
`

type RecordUpdateParams struct {
	FromVersion  string         `json:"from_version"`
	ToVersion    string         `json:"to_version"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

// Update history queries
// Record an update attempt (success or failure)
func (q *Queries) RecordUpdate(ctx context.Context, arg RecordUpdateParams) error {
	_, err := q.exec(ctx, q.recordUpdateStmt, recordUpdate,
		arg.FromVersion,
		arg.ToVersion,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}
