// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {logger} from '../models';

export function ChangeEncryptionKey(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<models.UpdateInfo>;

export function CheckForUpdateManual():Promise<models.UpdateInfo>;

export function ClearEncryptionKey():Promise<void>;

export function ClearPendingCSR(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateManualBackup():Promise<void>;

export function DeleteCertificate(arg1:string):Promise<void>;

export function DeleteLocalBackup(arg1:string):Promise<void>;

export function DownloadAndApplyUpdate():Promise<void>;

export function ExportBackup(arg1:boolean):Promise<void>;

export function ExportLogs():Promise<void>;

export function GenerateCSR(arg1:models.CSRRequest):Promise<models.CSRResponse>;

export function GetBuildInfo():Promise<Record<string, string>>;

export function GetCertificate(arg1:string):Promise<models.Certificate>;

export function GetCertificateChain(arg1:string):Promise<Array<models.ChainCertificateInfo>>;

export function GetCertificateHistory(arg1:string,arg2:number):Promise<Array<models.HistoryEntry>>;

export function GetConfig():Promise<models.Config>;

export function GetDataDirectory():Promise<string>;

export function GetLogInfo():Promise<logger.LogFileInfo>;

export function GetPendingPrivateKeyPEM(arg1:string):Promise<string>;

export function GetPrivateKeyPEM(arg1:string):Promise<string>;

export function GetSetupDefaults():Promise<models.SetupDefaults>;

export function GetUpdateHistory(arg1:number):Promise<Array<models.UpdateHistoryEntry>>;

export function ImportCertificate(arg1:models.ImportRequest):Promise<void>;

export function IsEncryptionKeyProvided():Promise<boolean>;

export function IsSetupComplete():Promise<boolean>;

export function IsWaitingForEncryptionKey():Promise<boolean>;

export function ListCertificates(arg1:models.CertificateFilter):Promise<Array<models.CertificateListItem>>;

export function ListLocalBackups():Promise<Array<models.LocalBackupInfo>>;

export function OpenBugReport():Promise<void>;

export function OpenDataDirectory():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PreviewCertificateUpload(arg1:string,arg2:string):Promise<models.CertificateUploadPreview>;

export function ProvideEncryptionKey(arg1:string):Promise<models.KeyValidationResult>;

export function ResetDatabase():Promise<void>;

export function RestartApp():Promise<void>;

export function RestoreFromBackup(arg1:models.BackupData):Promise<void>;

export function RestoreLocalBackup(arg1:string):Promise<void>;

export function SaveCSRToFile(arg1:string):Promise<void>;

export function SaveCertificateToFile(arg1:string):Promise<void>;

export function SaveChainToFile(arg1:string):Promise<void>;

export function SavePrivateKeyToFile(arg1:string):Promise<void>;

export function SaveSetup(arg1:models.SetupRequest):Promise<void>;

export function SetCertificateReadOnly(arg1:string,arg2:boolean):Promise<void>;

export function SkipEncryptionKey():Promise<void>;

export function UpdateCertificateNote(arg1:string,arg2:string):Promise<void>;

export function UpdateConfig(arg1:models.UpdateConfigRequest):Promise<models.Config>;

export function UpdatePendingNote(arg1:string,arg2:string):Promise<void>;

export function UploadCertificate(arg1:string,arg2:string):Promise<void>;

export function ValidateBackupFile(arg1:string):Promise<models.BackupValidationResult>;

export function ValidateEncryptionKeyForBackup(arg1:models.BackupData,arg2:string):Promise<void>;
