// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeEncryptionKey(arg1) {
  return window['go']['main']['App']['ChangeEncryptionKey'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckForUpdateManual() {
  return window['go']['main']['App']['CheckForUpdateManual']();
}

export function ClearEncryptionKey() {
  return window['go']['main']['App']['ClearEncryptionKey']();
}

export function ClearPendingCSR(arg1) {
  return window['go']['main']['App']['ClearPendingCSR'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateManualBackup() {
  return window['go']['main']['App']['CreateManualBackup']();
}

export function DeleteCertificate(arg1) {
  return window['go']['main']['App']['DeleteCertificate'](arg1);
}

export function DeleteLocalBackup(arg1) {
  return window['go']['main']['App']['DeleteLocalBackup'](arg1);
}

export function DownloadAndApplyUpdate() {
  return window['go']['main']['App']['DownloadAndApplyUpdate']();
}

export function EnrollOSNative() {
  return window['go']['main']['App']['EnrollOSNative']();
}

export function EnrollPasswordMethod(arg1, arg2) {
  return window['go']['main']['App']['EnrollPasswordMethod'](arg1, arg2);
}

export function ExportBackup(arg1) {
  return window['go']['main']['App']['ExportBackup'](arg1);
}

export function ExportCertificateZip(arg1, arg2) {
  return window['go']['main']['App']['ExportCertificateZip'](arg1, arg2);
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function GenerateCSR(arg1) {
  return window['go']['main']['App']['GenerateCSR'](arg1);
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetCertificate(arg1) {
  return window['go']['main']['App']['GetCertificate'](arg1);
}

export function GetCertificateChain(arg1) {
  return window['go']['main']['App']['GetCertificateChain'](arg1);
}

export function GetCertificateHistory(arg1, arg2) {
  return window['go']['main']['App']['GetCertificateHistory'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDataDirectory() {
  return window['go']['main']['App']['GetDataDirectory']();
}

export function GetLogInfo() {
  return window['go']['main']['App']['GetLogInfo']();
}

export function GetPendingPrivateKeyPEM(arg1) {
  return window['go']['main']['App']['GetPendingPrivateKeyPEM'](arg1);
}

export function GetPrivateKeyPEM(arg1) {
  return window['go']['main']['App']['GetPrivateKeyPEM'](arg1);
}

export function GetSetupDefaults() {
  return window['go']['main']['App']['GetSetupDefaults']();
}

export function GetUpdateHistory(arg1) {
  return window['go']['main']['App']['GetUpdateHistory'](arg1);
}

export function HasSecurityKeys() {
  return window['go']['main']['App']['HasSecurityKeys']();
}

export function ImportCertificate(arg1) {
  return window['go']['main']['App']['ImportCertificate'](arg1);
}

export function IsOSKeystoreAvailable() {
  return window['go']['main']['App']['IsOSKeystoreAvailable']();
}

export function IsSetupComplete() {
  return window['go']['main']['App']['IsSetupComplete']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function IsWaitingForEncryptionKey() {
  return window['go']['main']['App']['IsWaitingForEncryptionKey']();
}

export function ListCertificates(arg1) {
  return window['go']['main']['App']['ListCertificates'](arg1);
}

export function ListLocalBackups() {
  return window['go']['main']['App']['ListLocalBackups']();
}

export function ListSecurityKeys() {
  return window['go']['main']['App']['ListSecurityKeys']();
}

export function NeedsMigration() {
  return window['go']['main']['App']['NeedsMigration']();
}

export function OpenBugReport() {
  return window['go']['main']['App']['OpenBugReport']();
}

export function OpenDataDirectory() {
  return window['go']['main']['App']['OpenDataDirectory']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PreviewCertificateUpload(arg1, arg2) {
  return window['go']['main']['App']['PreviewCertificateUpload'](arg1, arg2);
}

export function ProvideEncryptionKey(arg1) {
  return window['go']['main']['App']['ProvideEncryptionKey'](arg1);
}

export function RemoveSecurityKey(arg1) {
  return window['go']['main']['App']['RemoveSecurityKey'](arg1);
}

export function ResetDatabase() {
  return window['go']['main']['App']['ResetDatabase']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RestoreFromBackup(arg1) {
  return window['go']['main']['App']['RestoreFromBackup'](arg1);
}

export function RestoreLocalBackup(arg1) {
  return window['go']['main']['App']['RestoreLocalBackup'](arg1);
}

export function SaveCSRToFile(arg1) {
  return window['go']['main']['App']['SaveCSRToFile'](arg1);
}

export function SaveCertificateToFile(arg1) {
  return window['go']['main']['App']['SaveCertificateToFile'](arg1);
}

export function SaveChainToFile(arg1) {
  return window['go']['main']['App']['SaveChainToFile'](arg1);
}

export function SavePrivateKeyToFile(arg1) {
  return window['go']['main']['App']['SavePrivateKeyToFile'](arg1);
}

export function SaveSetup(arg1) {
  return window['go']['main']['App']['SaveSetup'](arg1);
}

export function SetCertificateReadOnly(arg1, arg2) {
  return window['go']['main']['App']['SetCertificateReadOnly'](arg1, arg2);
}

export function SkipEncryptionKey() {
  return window['go']['main']['App']['SkipEncryptionKey']();
}

export function TryAutoUnlock() {
  return window['go']['main']['App']['TryAutoUnlock']();
}

export function UpdateCertificateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateCertificateNote'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdatePendingNote(arg1, arg2) {
  return window['go']['main']['App']['UpdatePendingNote'](arg1, arg2);
}

export function UploadCertificate(arg1, arg2) {
  return window['go']['main']['App']['UploadCertificate'](arg1, arg2);
}

export function ValidateBackupFile(arg1) {
  return window['go']['main']['App']['ValidateBackupFile'](arg1);
}

export function ValidateEncryptionKeyForBackup(arg1, arg2) {
  return window['go']['main']['App']['ValidateEncryptionKeyForBackup'](arg1, arg2);
}
